-   repo: git@github.com:pre-commit/pre-commit-hooks
    sha: d3db0385825d4c082bc7117c090ac16cb4840f3e
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: autopep8-wrapper
        args: ['-i', '--ignore=E265,E309,E501']
    -   id: debug-statements
    -   id: name-tests-test
        files: ^tests/.+\.py$
    -   id: flake8
-   repo: git@github.com:pre-commit/mirrors-jshint
    sha: e86225836aadd058036f47a6de9b0ee0440476eb
    hooks:
    -   id: jshint
        language_version: 4.2.1
